
[build]
  publish = "dist"
  command = "npm ci --include=optional && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_INCLUDE = "optional"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[context.production]
  environment = { VITE_ENVIRONMENT = "production" }

[context.staging]
  environment = { VITE_ENVIRONMENT = "staging" }

[context.deploy-preview]
  environment = { VITE_ENVIRONMENT = "staging" }
