name: Lighthouse CI

on:
  workflow_run:
    workflows: ["Deploy to Vercel"]
    types:
      - completed

jobs:
  lighthouse:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Run Lighthouse CI on Production URL
        run: |
          lhci autorun --collect.url=https://app.senhorsorriso.com.br --upload.target=temporary-public-storage

      - name: Output Lighthouse report link
        run: |
          echo "Veja o relatório Lighthouse no link gerado acima."
          
          {
  // ...existing config...
  "compilerOptions": {
    // ...existing options...
    "types": ["jest"]
  }
}
